### ISSUE TITLE
0725 지도 활용 통계 구현

### ISSUE THREAD

**Issue by loveyrooney** [chunjaeTIVE/TIVE#102]
#### 지도 활용 통계 구현
- [x] 지도 api + 공공 데이터 api 불러와서 나의 현위치 주변 학교 탐색 
- [x] 페이지 UI 
- [x] 통계 로직 구현

**Comment by tongueEye** [comment]
1. 초기 위치 기준
 - 가입할 때 입력받은 교육청 코드를 기준으로 교육청 위치로 위치 초기화

 2. 기능 내용
 - 네이버 지도와 학교 위치정보 open api 사용하여 유저의 해당 지역에 있는 학교들 위치를 마커로 찍어줌
 - 헤더 메뉴에서 지역별 랭킹 클릭하면 해당 화면 나오도록 수정

 3. 앞으로 구현할 내용
 - 지역별 평균으로 랭킹 순위를 보여줄 예정
 - UI 디자인 및 구현
 - 학교 로고 수집
