### ISSUE TITLE
시험지 로직 완성(김혜연, 황현준)

### ISSUE THREAD

**Issue by loveyrooney** [chunjaeTIVE/TIVE#12]
#### front 단 
- [x] 푼 문제 우측 슬라이드 번호 색깔 동적 변경 (현준)
- [x] **서버 시간 기준 남은 시간 카운트 작업 (현준)**
- [x] 문항 유형 구분작업 및 문항 유형별 정답 추출 메서드 만들기 (혜연)
- [x] js 코드 정리 (같이)

#### back 단
- [x] 시험지 단위로 문제 가져오기 (examname, itemcount, qid, order, ordername, qcontents, qtype) (현준)
- [x] 시험지 안에 딸린 이미지 / 음성 파일 처리 (현준)
- [x] **최종 제출 처리 (응시 시작 시 user test insert / 응시 완료 시 user answer bulk insert && user test countCorrect update) (혜연)**
- [x] **시험 안내 화면 응시/재응시 버튼 처리 (현준)**
- [x] 채점 처리 (혜연)

**Comment by loveyrooney** [comment]
7/17 완료 
js 코드 정리 (같이)
시험지 단위로 문제 가져오기 (examname, itemcount, qid, order, ordername, qcontents, qtype) (현준)
a013a41f469b8ec06e9bfa9aaaa94678e9d4d018

서버 시간 기준 남은 시간 카운트 작업 (현준) 5eb3967cda20012c4433dec4ccbe0edf6ec8613d
인풋 유형별 정답 받기 (혜연) d86b62feb4aea82b6781911fac358e33cd2537d9

**Comment by loveyrooney** [comment]
7/18 완료
시험지 안에 딸린 이미지 / 음성 파일 처리 (현준) 807a7cf4b27bec38bd7dabdce12917c703adc1ed
일부 문제 css 깨지는 현상 복구 (현준) 904631c39698625eef7d1f2f8018bf9388658019
문항 유형 구분작업 및 문항 유형별 정답 추출 메서드 만들기 (혜연) 1bb7775988f2f416aea6a381c9645a58f756c75d
=> 정답 유형 button 타입이 또 있어서 정답 받기 및 유형별 최종 시험지 결과 템프 변수 및 메서드화 fc36af8dd7d7a970ef04b742847e7c562eca2fac

**Comment by loveyrooney** [comment]
7/19 완료
img drag drop 유형과 text drag drop 정답 추출 통합, 일부 작동 안하는 select 유형 수정 (혜연)  20316bad968a8f359970f99bed385098e0722fd6
시험지별 class 정리 (현준) b751f3750493fdf5997b70cf86eb7683e658c9a9
시험지별 응시 시간에 따른 제한시간 작업, 시험지별 라우팅 작업 (현준) fd5c6d0acf4748e31ac93750cf85e4c7c54c8e3e

**Comment by loveyrooney** [comment]
7/20 완료 (혜연)
drag drop 시 한 칸 안에 여러 개 선택되는 문제 유효성 검사 처리
drag drop, hotspot 유형 번호 하나에 통합하고 최종 제출을 위한 정답 리스트 생성 
최종 제출 서버 fetch 요청 처리 (일단 controller 에서 받게만 해둠) 
5add6ce5bd671d34525ccc736d5f686837ec5c5e

**Comment by skd9712** [comment]
7/20
swiper-pagination-buller 클래스마다 id를 만들어 구분 2e3691f492b81ca3da543a06c84575c064860e81

**Comment by skd9712** [comment]
7/22
모든 유형별 푼문제 체크 완료

**Comment by loveyrooney** [comment]
7/24 
최종 제출 및 채점, DB 추가 로직 완료 2e3691f492b81ca3da543a06c84575c064860e81
