### ISSUE TITLE
0712 덤프데이터 추출 및 테스트

### ISSUE THREAD

**Issue by skd9712** [chunjaeTIVE/TIVE#5]
* 내일 할 일
1. dump data 계속 분석해서 user 정답 결과 console에 찍기⭐⭐⭐⭐⭐
2. erd 최종 확정 후 rds 구축 및 엔티티 설계

* 질문 사항
1. dump파일 tb_item_on테이블의  **item_content, item_contents** 컬럼이 같은 내용을 저장함 
   => erd에선 item_content_html 컬럼으로 받는데, 두개로 나눈 이유와 하나로 해도 되는지?

1-1. 관리자 페이지에서는 문제를 생성할 때 지문과 발문이 나뉘어져 있는데, 한 컬럼에 묶어서 써도 되는지?

2. 그래프 완성형 문제 하나 있는데 생략 해도 되는지?

3. select 쿼리 4개를 union all로 한 번에 사용할 때, 병목 현상 발생 여부와 장/단점이 무엇인지?

4. 전날 질문
- 국가수준 학업성취도 평가는 중3, 고2만 보게 되어있고 기초학력 진단평가는 초/중/고 로 되어있는데
우리 서비스 학교급 기준 어떻게 정해야 하는건지
- 프론트/백 나눠서 역할분담하는 것과 풀스택을 기능단위로 나누는 역할분담 중에 어떤것이 좋을지
- wbs 역할분담 이런식으로 해도 되는건지
- 이 프로젝트 실제 개발기간 얼마나 걸렸는지
- 전 기수에서 관리자 기능까지 구현한 팀이 있는지

**Comment by ppodaejang** [comment]
### 오늘 한일

문제 유형 별 선택된 정답 값을 화면에 받아오기
덤프데이터 분석
메인페이지 UI 디자인 완료
리포트 페이지 샘플데이터로 테스트 시작
스프링 시큐리티 연동 테스트
